### ISSUE TITLE
Jscs has many 'babylon' dependencies and cannot be installed

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#11]
Jscs has this kind of problematic babylon depency-hell. 

<pre>
npm(babylon) >= 6.7.0   
npm(babylon) < 7.0.0    
npm(babylon) >= 6.3.0   
</pre>

I tried to fix it with with

<pre>
%nodejs_fixdep babylon "~6.7"
</pre>

without success.

package can be found: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/jscs

**Comment by illuusio** [comment]
Same sort of problem is with 'postcss-cli' can't full fill commander dependency
 https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/postcss-cli

**Comment by marguerite** [comment]
@illuusio 

Hi, I've been AFK for a while. I'll check that soon.

**Comment by marguerite** [comment]
@illuusio 

Hi, sorry for the long AFK.

Recently I've been rewriting nodejs-packaging and npkg into standard rubygem (yes over a year my ruby programming capability advanced!)

I re-designed the json structure, made it more reliable and easy to debug. I have resolved the biggest headache which is finding parents in json.

So you'll see an usable nodejs-packaging in one month (I finish the npkg tool now)

Marguerite

**Comment by illuusio** [comment]
As I packaged some Nodejs packages with old one I salut if there will be new dependency parser because it's biggest headache currently.

**Comment by marguerite** [comment]
@illuusio yes...that's why I decide to rewrite it to node2rpm...basically a few headaches in front of node module packaging: 

* parse module versions 

why module versions become a problem since they follow semver.org? because old versions don't. so many weird and laughable old version strings that are hard to believe exist on the npmjs registry server. eg: 7.0.0-beta.0-ranges or 3.0.0-blind-testing or 2.0.0-prerelease-1+build20131010...

* break the dependency loop if a module's dependencies and dependencies of the dependencies require the module itself. it's hard to imagine in C/C++ world...but exists everywhere in nodejs. So you need to be able to recognize the parent path (parent, grandparent, ..., till the root element), while finding the parent for a json object is a blank area in Ruby/other languages so no existing module can be used...I just design my own data structure and write my own parser.

**Comment by marguerite** [comment]
@illuusio it may take longer time because I want to have node2rpm produce/update specfiles...so you don't need to do the copy work...

**Comment by illuusio** [comment]
Note if you need some help or testing. It would neat to have some way to back out of npm packages like Atom.

**Comment by hurricanehrndz** [comment]
@marguerite,

First of thank you so much for the wonderful program you have created. I recently started re-writing some of this program, I had been under the impression that it was abandoned since it had been a long time you had responded.

Anyhow, I would like to help. Here are some of the issues that I believe need be address or features that need be added, which I was on my way to completing:

-  Missing minor or patch number = wildcard.
    To be more accurate the missing numbers are supposed to be desugar to
    zero, like they were but also allow for flexibility. Hence, why
    wildcards are better than zero in the code.
    https://github.com/npm/node-semver

-  automatic spec generation, emulate what py2pack does for generation of spec for the various distros:
 https://github.com/openSUSE/py2pack/tree/master/py2pack/templates

- dedupe the installation tree and flatten, emulating what npm multi-stage install did, see here
https://github.com/npm/npm/issues/5919
https://docs.npmjs.com/cli/dedupe

- add unit test to ensure code is working as expected
- shrink sizes of functions and methods ---> following clean code philosophy http://swreflections.blogspot.ca/2012/12/rule-of-30-when-is-method-class-or.html

Please do not take this the wrong way. Like I have said, what you accomplished was amazing, I would like to help make it better though. Perhaps we can make a list of issues and features and fixes that need to be applied and we can both work on it.

I also put a lot of thought into the whole dependency tree issue. You are trying to replicate a lot of npm's functionality. So why not consider using npm? Instead of replicating the code and functionality, which ties the project into whatever changes it is that they make, one could just leverage npm like so,

1. create a temp directory in var for install and cache
2. install the node package into the temp directory, using verbosity
3. from the output of the npm install parse the versions of dependency hell
4. walk the install directory to gather the ideal and dedupe install tree
5. collect source files from cache directory

**Comment by marguerite** [comment]
@hurricanehrndz 

Thanks!

about the features you mentioned:

* I wrote a 100% compatible "rubygem-node-semver": https://github.com/marguerite/rubygem-node-semver. so the problem has been identified and solved.

* I just add spec generation feature for https://github.com/marguerite/rubygem-node2rpm tonight. 

But It will just create from zero. As you know, we bundle nodejs dependencies so there'll be a lot of "SourceN" tags. And they are different among different releases. So an "update specfile" feature is a must. That means I need to write a RPM specfile parser in Ruby first (there's no such gem yet). 

* I'll take a look at "dedupe"

* unit test will be done of course. Any way it's a standard gem and tests with "spec" should be added. I just leave that later.

* yes, during the rewrite, I use modules/classes, so the coding style looks good now. but I'll read the post you shared.

**Comment by marguerite** [comment]
And the reasons why I didn't use npm:

1.

Back to when I created this project, the npm for openSUSE is not bundled into nodejs itself. but separately packaged with 200+ modules. and it always broke. so at that time I have no way to install the distribution's npm. That's why I think my program must "can work" without npm from the beginning.

Someday npm for openSUSE might be split and made to a bundle with my tool. I don't want packagers to bother with the chicken & egg problem. 

2.

Actually I think having nodejs installed locally to package nodejs stuff that build remotely on the build machine just not sound good. Because we have openSUSE Build Service, the way, build it locally first and then package, hasn't been an option for packagers for a long time.

3.

And npm itself is not clean enough actually. my reworked implementation has these features that npm doesn't have (but you can also get it by you idea because you actually just install the module...):

* my implementation has a license tag for every dependency...so I can pick them up, remove the duplicates, and form a license string "MIT AND ISC AND BSD-3-Clause" for the bundle. which is accurate. In you way...you have to unpack every tarball to get that string.

* in my implementation, if a dependency with the same version occurs again. the existing one will be deleted. and a new one is created under the common parent of the two. eg: a->b->d->e->minimist and a->b->c->minimist, then minimist will be created under b. I don't know if npm has this, but I'm proud of my flat implementation.

Anyway...I think we should not implement a packaging tool that depends on npm...eg gem2rpm doesn't use the rubygem at all. because no one would like to be like a garbage collector hahaha...

There're realistic reasons for this, if we depends on npm, then how fast you can package a module will highly depend on how fast you can download...it's just boring and not suitable for later maintenance eg I may create another tool that massively and automatically update all the nodejs modules in devel:languages:nodejs.

**Comment by marguerite** [comment]
well, seems I have implemented the dedupe feature occasionally...

**Comment by hurricanehrndz** [comment]
Yes multi-stage install included a flattening of the dependency tree. So far the work you have done is amazing and I'm really impressed. You should be congratulated for your efforts.

ha ha, I totally feel you on the chicken before the egg scenario, that is why I had forked your project and started writing unit tests. I wanted to safely start refactoring the code. I knew I could write a packaging tool that depend on npm, but it killed me a little inside to do it, so I refrained. I'm glad you felt the same way.

**Comment by hurricanehrndz** [comment]
I have read the new code and so far it looks leap and bonds ahead of what you had accomplished before. I'm no ruby programmer and the fact that I can read the code tells me its 100% better. I can start perhaps writing some test for the code, which framework where you hoping to use? Minitest or rspec?

The only suggestion I would make is adhere closer to ruby-style-guide:
https://github.com/bbatsov/ruby-style-guide

Specifically

> Use two spaces per indentation level (aka soft tabs). No hard tabs.

**Comment by marguerite** [comment]
remember to fork the rework project that is node2rpm. In the future nodejs-packaging will contain the RPM macros only...all functional stuff will be moved/ported into node2rpm

**Comment by hurricanehrndz** [comment]
Will do, is there a specific test framework you wish to use?

**Comment by marguerite** [comment]
Rspec is the only test framework I am familiar with...

Yes, and I should run RubyCop with my codes and configure my vi...(yes I just write codes with vi)...

**Comment by hurricanehrndz** [comment]
I love vim too, and only use vim to write code.  See here:
https://i.redd.it/e9ipexyz6chy.png

Just read the intersect code which is your equivalent to npm's dedupe, really awesome code! I have quite a bit to do in order to learn ruby fully, but I do code in other languages.

**Comment by hurricanehrndz** [comment]
Well I have to say, you have everything under control. There is not much I can add.  Please let us know once you have the rpms up on the build service.

**Comment by hurricanehrndz** [comment]
Just wondering how close to a release are you?

**Comment by marguerite** [comment]
about one week. you can see the files deleted are the files I implemented in node2rpm.

**Comment by illuusio** [comment]
As this seems to be resolved.. closing
