### ISSUE TITLE
npkg overrides version setting in .spec file

### ISSUE THREAD

**Issue by coogor** [marguerite/nodejs-packaging#13]
I'm building Application:ERP:Tryton:3.8/tryton-sao. 
In the spec file we have 
%define majorver 3.8
Version:        %{majorver}.5

When running npkg trytod-sao , it downloads version 4.0.1 and builds against that - this will not work in the 3.8 tree. npkg should recognize the version in the spec file

**Comment by marguerite** [comment]
nope. 

npkg has nothing to do with the spec file. it is just a tool to create some files, which can be used to fill your spec file by yourself.

in theory, it's an update tool. which means it doesn't need to know the version. it just fetch the latest. it's decided by the actual packager whether or not to use its generated files. that's why it is a helper.

in this case, if you want 3.8:
- update to 3.8 when it was the latest and stick to it.
- do not use npkg. you can modify the files genenrated for 4.0 manually and upload to 3.8 branch. eg:

from http://registry.npmjs.org/tryton-sao you'll know tryton-sao 3.8 depends on bower ^1.4.1, and in bower.json you'll know what the bower_components.tar.gz should look like.

**Comment by marguerite** [comment]
You can raise a new feature request for npkg to support versioned fetch. but it's certainly not a fix in this case. sorry.

**Comment by marguerite** [comment]
@coogor 

Hi, I've been reworking npkg in github.com/marguerite/rubygem-npkg. now it supports versioned fetch. will release soon when I finish the refactor.
